### ISSUE TITLE
Requiring strategies broken on case sensitive file systems

### ISSUE THREAD

**Issue by thefotios** [intesso/connect-locale#1]
Before strategies are loaded [here](https://github.com/intesso/connect-locale/blob/master/server.js#L44), there are passed through the `cleanupArray` function. The problem is that this lowercases the names before sent into `require`. So even though I am passing in `acceptLanguage` as the strategy, it throws this error:

```
Error: Cannot find module './lib/strategy/acceptlanguage'
```

Not sure what problem that was trying to solve, but a simple solution could just be renaming the file to be all lowercase. Otherwise, you could just require people pass in explicit values and don't hold their hands.

**Comment by andineck** [comment]
I'm not 100% sure if I understood correctly.
If you use it like in the example in the Readme:

``` js
    getLocaleFrom: ['path', 'cookie', 'acceptLanguage'],
```

is it working then?

**Comment by andineck** [comment]
Ah, now I see, the problem is as you mentioned in the `toLowerCase` function call inside of the `cleanupArray` function [here](https://github.com/intesso/connect-locale/blob/master/server.js#L57). 

I added a test, which should fail on linux. I'm running on mac, so it does not fail... arrrrghh.

**Comment by andineck** [comment]
fixed in version 1.3.0 in npm.

Thank you for reporting the bug.

**Comment by thefotios** [comment]
Thanks for fixing it. I hit it in the middle of a hackathon and everybody else thought I was crazy because it worked for them on their Macs.

Fun hackaround for your `package.json` or anybody else who's including it

``` json
 "postinstall": "(cd ./lib/strategy; if [ ! -f acceptlanguage.js ]; then ln -sf acceptLanguage.js acceptlanguage.js; fi)"
```

**Comment by andineck** [comment]
Hope your hackathon went well :-) 
Thx for sharing the workaround solution.
